name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Project 1
        run: curl -I https://wmqkbwcholvnbpnuqnzm.supabase.co/rest/v1/

      - name: Ping Project 2
        run: curl -I https://aovyugcxrrkjkzauoomb.supabase.co/rest/v1/

      - name: Ping Project 3
        run: curl -I https://kcueevrfdkbvkgjpyzuo.supabase.co/rest/v1/

      - name: Ping Project 4
        run: curl -I https://cdhykgvciawzfubalxdu.supabase.co/rest/v1/

      - name: Ping Project 5
        run: curl -I https://epsygtwxjbqrxseerglh.supabase.co/rest/v1/

      - name: Ping Project 6
        run: curl -I https://hoxkdprdovurlvfyzpdo.supabase.co/rest/v1/
